## CURVATURE
default:
  # shader affects retroarch shaders
  shader: _custom-presets/crt-geom-softcorners
  # scanline affect fba2x
  scanline: true
# Nintendo
snes:
  shader: _custom-presets/crt-geom-softcorners
snes-msu:
  shader: _custom-presets/crt-geom-softcorners
nes:
  shader: _custom-presets/crt-geom-softcorners
n64:
  shader: _custom-presets/enhanced-curvature
satellaview:
  shader: _custom-presets/crt-geom-softcorners
sufami:
  shader: _custom-presets/crt-geom-softcorners
gba:
  shader: handheld/lcd-grid-v2-gba-color
gb:
  shader: handheld/gameboy
gbc:
  shader: handheld/lcd-grid-v2-gbc-color
nds:
  shader: handheld/lcd-grid-v2-nds-color
3ds:
  shader: handheld/lcd-shader
fds:
  shader: _custom-presets/crt-geom
virtualboy:
  shader: retro/sharp-bilinear-scanlines
gc:
  shader: _custom-presets/crt-geom-softcorners
wii:
  shader: _custom-presets/crt-geom-softcorners
# Sega
dreamcast:
  shader: _custom-presets/crt-geom-softcorners
sg1000:
  shader: _custom-presets/crt-geom-softcorners
mastersystem:
  shader: _custom-presets/crt-geom-softcorners
megadrive:
  shader: _custom-presets/crt-geom-softcorners
gamegear:
  shader: crt-guest-dr-venom-fast
sega32x:
  shader: _custom-presets/crt-geom-softcorners
segacd:
  shader: _custom-presets/crt-geom-softcorners
saturn:
  shader: _custom-presets/crt-geom-softcorners
# Arcade
arcade:
  shader: _custom-presets/crt-geom-arcade
cps1:
  shader: _custom-presets/crt-geom-arcade
cps2:
  shader: _custom-presets/crt-geom-arcade
cps3:
  shader: _custom-presets/crt-geom-arcade
neogeo:
  shader: _custom-presets/crt-geom-arcade
neogeocd:
  shader: _custom-presets/crt-geom-softcorners
mame:
  shader: _custom-presets/crt-geom-arcade
fba:
  shader: _custom-presets/crt-geom-arcade
naomi:
  shader: _custom-presets/crt-geom-arcade
atomiswave:
  shader: _custom-presets/crt-geom-arcade
#
3do:
  shader: _custom-presets/crt-geom-softcorners
ngp:
  shader: handheld/zfast-lcd
ngpc:
  shader: handheld/zfast-lcd
gw:
  shader: _custom-presets/crt-geom-softcorners
vectrex:
  shader: retro/sharp-bilinear-scanlines
lynx:
  shader: crt-guest-dr-venom-fast
lutro:
  shader: _custom-presets/crt-geom-softcorners
wswan:
  shader: handheld/zfast-lcd
wswanc:
  shader: handheld/zfast-lcd
pcengine:
  shader: _custom-presets/crt-geom-softcorners
pcenginecd:
  shader: _custom-presets/crt-geom-softcorners
supergrafx:
  shader: _custom-presets/crt-geom-softcorners
atari800:
  shader: _custom-presets/crt-geom-softcorners
atari2600:
  shader: _custom-presets/crt-geom-softcorners
atari5200:
  shader: _custom-presets/crt-geom-softcorners
atari7800:
  shader: _custom-presets/crt-geom-softcorners
prboom:
  shader: _custom-presets/crt-geom-softcorners
psx:
  shader: _custom-presets/crt-geom-softcorners
ps2:
  shader: _custom-presets/crt-geom-softcorners
psp:
  shader: handheld/lcd-grid-v2-psp-color
colecovision:
  shader: _custom-presets/crt-geom-softcorners
jaguar:
  shader: _custom-presets/crt-geom-softcorners
lightgun:
  shader: _custom-presets/crt-geom-softcorners
# Computers
lutro:
  shader: _custom-presets/crt-geom-softcorners
msx:
  shader: _custom-presets/crt-geom-softcorners
msx1:
  shader: _custom-presets/crt-geom-softcorners
msx2:
  shader: _custom-presets/crt-geom-softcorners
msx2+:
  shader: _custom-presets/crt-geom-softcorners
amiga:
  shader: _custom-presets/crt-geom-softcorners
amiga1200:
  shader: _custom-presets/crt-geom-softcorners
amiga500:
  shader: _custom-presets/crt-geom-softcorners
amigacd32:
  shader: _custom-presets/crt-geom-softcorners
amigacdtv:
  shader: _custom-presets/crt-geom-softcorners
c20:
  shader: _custom-presets/crt-geom-softcorners
c64:
  shader: _custom-presets/crt-geom-softcorners
c128:
  shader: _custom-presets/crt-geom-softcorners
cave:
  shader: _custom-presets/crt-geom-softcorners
dos:
  shader: _custom-presets/crt-geom-softcorners
amstradcpc:
  shader: _custom-presets/crt-geom-softcorners
atarist:
  shader: _custom-presets/crt-geom-softcorners
zx81:
  shader: _custom-presets/crt-geom-softcorners
zxspectrum:
  shader: _custom-presets/crt-geom-softcorners
odyssey2:
  shader: _custom-presets/crt-geom-softcorners
zx81:
  shader: _custom-presets/crt-geom-softcorners
pcfx:
  shader: _custom-presets/crt-geom-softcorners
x68000:
  shader: _custom-presets/crt-geom-softcorners
o2em:
  shader: _custom-presets/crt-geom-softcorners
scummvm:
  shader: _custom-presets/crt-geom-softcorners
pc98:
  shader: _custom-presets/crt-geom-softcorners
pcfx:
  shader: _custom-presets/crt-geom-softcorners
thomson:
  shader: _custom-presets/crt-geom-softcorners
