## CURVATURE
default:
  # shader affects retroarch shaders
  shader: crt/crt-geom
  # scanline affect fba2x
  scanline: true
snes:
  shader: crt/crt-geom
snes-msu:
  shader: crt/crt-geom
nes:
  shader: crt/crt-geom
n64:
  shader: crt/crt-geom
gba:
  shader: handheld/zfast-lcd
gb:
  shader: handheld/zfast-lcd
gbc:
  shader: handheld/zfast-lcd
nds:
  shader: handheld/lcd-grid-v2-nds-color
3ds:
  shader: handheld/lcd-shader
fds:
  shader: crt/crt-geom
virtualboy:
  shader: retro/sharp-bilinear-scanlines
# Sega
dreamcast:
  shader: crt/crt-geom-deinterlaced
sg1000:
  shader: crt/crt-geom
mastersystem:
  shader: crt/crt-geom
megadrive:
  shader: crt/crt-geom
gamegear:
  shader: handheld/zfast-lcd
sega32x:
  shader: crt/crt-geom
segacd:
  shader: crt/crt-geom
# Arcade
neogeo:
  shader: crt/crt-geom
neogeocd:
  shader: crt/crt-geom
mame:
  shader: crt/crt-geom
fba:
  shader: crt/crt-geom
naomi:
  shader: crt/crt-geom-deinterlaced
atomiswave:
  shader: crt/crt-geom-atomiswave
#
ngp:
  shader: handheld/zfast-lcd
ngpc:
  shader: handheld/zfast-lcd
gw:
  shader: crt/crt-geom
vectrex:
  shader: retro/sharp-bilinear-scanlines
lynx:
  shader: handheld/zfast-lcd
lutro:
  shader: crt/crt-geom
wswan:
  shader: handheld/zfast-lcd
wswanc:
  shader: handheld/zfast-lcd
pcengine:
  shader: crt/crt-geom
pcenginecd:
  shader: crt/crt-geom
supergrafx:
  shader: crt/crt-geom
atari800:
  shader: crt/crt-geom
atari2600:
  shader: crt/crt-geom
atari5200:
  shader: crt/crt-geom
atari7800:
  shader: crt/crt-geom
prboom:
  shader: crt/crt-geom
psx:
  shader: crt/crt-geom
colecovision:
  shader: crt/crt-geom
# Computers
msx:
  shader: crt/crt-geom
msx1:
  shader: crt/crt-geom
msx2:
  shader: crt/crt-geom
amiga:
  shader: crt/crt-geom
amstradcpc:
  shader: crt/crt-geom
atarist:
  shader: crt/crt-geom
zxspectrum:
  shader: crt/crt-geom
odyssey2:
  shader: crt/crt-geom
zx81:
  shader: crt/crt-geom
pcfx:
  shader: crt/crt-geom
x68000:
  shader: crt/crt-geom
