## SCANLINES
default:
  # shader affects retroarch shaders
  shader: scanlines/scanlines-enhanced
  # scanline affect fba2x
  scanline: true
# Nintendo
snes:
  shader: scanlines/scanlines-enhanced
snes-msu:
  shader: scanlines/scanlines-enhanced
nes:
  shader: scanlines/scanlines-enhanced
n64:
  shader: interpolation/sharp-bilinear-scanlines
satellaview:
  shader: scanlines/scanlines-enhanced
sufami:
  shader: scanlines/scanlines-enhanced
gba:
  shader: handheld/lcd-grid-v2
gb:
  shader: handheld/lcd-grid-v2
gbc:
  shader: handheld/lcd-grid-v2
nds:
  shader: handheld/lcd-grid-v2-nds-color
3ds:
  shader: handheld/lcd-shader
fds:
  shader: scanlines/scanlines-enhanced
virtualboy:
  shader: retro/sharp-bilinear-scanlines
gc:
  shader: anti-aliasing/fxaa
wii:
  shader: anti-aliasing/fxaa
# Sega
dreamcast:
  shader: anti-aliasing/fxaa
sg1000:
  shader: scanlines/scanlines-enhanced
mastersystem:
  shader: scanlines/scanlines-enhanced
megadrive:
  shader: scanlines/scanlines-enhanced
gamegear:
  shader: handheld/lcd-grid-v2
sega32x:
  shader: scanlines/scanlines-enhanced
segacd:
  shader: scanlines/scanlines-enhanced
saturn:
  shader: scanlines/scanlines-enhanced
# Arcade
arcade:
  shader: scanlines/scanlines-enhanced
cps1:
  shader: scanlines/scanlines-enhanced
cps2:
  shader: scanlines/scanlines-enhanced
cps3:
  shader: scanlines/scanlines-enhanced
neogeo:
  shader: scanlines/scanlines-enhanced
neogeocd:
  shader: scanlines/scanlines-enhanced
mame:
  shader: scanlines/scanlines-enhanced
fba:
  shader: scanlines/scanlines-enhanced
naomi:
  shader: scanlines/scanlines-enhanced
atomiswave:
  shader: scanlines/scanlines-enhanced
#
3do:
  shader: scanlines/scanlines-enhanced
ngp:
  shader: handheld/lcd-grid-v2
ngpc:
  shader: handheld/lcd-grid-v2
gw:
  shader: handheld/lcd-grid-v2
vectrex:
  shader: scanlines/scanlines-enhanced
lynx:
  shader: handheld/lcd-grid-v2
lutro:
  shader: scanlines/scanlines-enhanced
wswan:
  shader: handheld/lcd-grid-v2
wswanc:
  shader: handheld/lcd-grid-v2
pcengine:
  shader: scanlines/scanlines-enhanced
pcenginecd:
  shader: scanlines/scanlines-enhanced
supergrafx:
  shader: scanlines/scanlines-enhanced
atari800:
  shader: scanlines/scanlines-enhanced
atari2600:
  shader: scanlines/scanlines-enhanced
atari5200:
  shader: scanlines/scanlines-enhanced
atari7800:
  shader: scanlines/scanlines-enhanced
prboom:
  shader: scanlines/scanlines-enhanced
psx:
  shader: scanlines/scanlines-enhanced
ps2:
  shader: scanlines/scanlines-enhanced
psp:
  shader: handheld/lcd-grid-v2
colecovision:
  shader: scanlines/scanlines-enhanced
jaguar:
  shader: scanlines/scanlines-enhanced
lightgun:
  shader: scanlines/scanlines-enhanced
# Computers
lutro:
  shader: scanlines/scanlines-enhanced
msx:
  shader: scanlines/scanlines-enhanced
msx1:
  shader: scanlines/scanlines-enhanced
msx2:
  shader: scanlines/scanlines-enhanced
amiga:
  shader: scanlines/scanlines-enhanced
amiga1200:
  shader: scanlines/scanlines-enhanced
amiga500:
  shader: scanlines/scanlines-enhanced
amigacd32:
  shader: scanlines/scanlines-enhanced
amigacdtv:
  shader: scanlines/scanlines-enhanced
c20:
  shader: scanlines/scanlines-enhanced
c64:
  shader: scanlines/scanlines-enhanced
c128:
  shader: scanlines/scanlines-enhanced
cave:
  shader: scanlines/scanlines-enhanced
cps1:
  shader: scanlines/scanlines-enhanced
cps3:
  shader: scanlines/scanlines-enhanced
dos:
  shader: scanlines/scanlines-enhanced
amstradcpc:
  shader: scanlines/scanlines-enhanced
atarist:
  shader: scanlines/scanlines-enhanced
zx81:
  shader: scanlines/scanlines-enhanced
zxspectrum:
  shader: scanlines/scanlines-enhanced
odyssey2:
  shader: scanlines/scanlines-enhanced
zx81:
  shader: scanlines/scanlines-enhanced
pcfx:
  shader: scanlines/scanlines-enhanced
x68000:
  shader: scanlines/scanlines-enhanced
o2em:
  shader: scanlines/scanlines-enhanced
scummvm:
  shader: scanlines/scanlines-enhanced
pc98:
  shader: scanlines/scanlines-enhanced
pcfx:
  shader: scanlines/scanlines-enhanced
thomson:
  shader: scanlines/scanlines-enhanced
